server:
  port: 8762
spring:
  application:
    name: service-register
eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
